services:
  - type: web
    name: pharmacy-backend
    env: docker
    plan: free
    region: oregon
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Development
      - key: ConnectionStrings__DefaultConnection
        value: "Server=dummy;Database=dummy;User Id=dummy;Password=dummy;"
